### ISSUE TITLE
tech-debt: Consider moving shared get version from lerna.json or package.json to own action

### ISSUE THREAD

**Issue by Zidious** [dequelabs/axe-api-team-public#115]
We use the following snippet for getting a version in more than one action. As it's fairly simple we can move it to its own shell script action: 

```yml
- name: Get version
  shell: bash
  id: get-version
  run: |
    # Get the version number from the prepare_release shell script and set it as an output
    # Monorepos have a lerna.json file that contains the updated version number
    # Non-monorepos, or non-npm repos, have a package.json file that contains the updated version number
    if [ -f "lerna.json" ]; then
      echo "release_candidate_version=$(cat lerna.json | jq -r '.version')" >> $GITHUB_OUTPUT
    else
      echo "release_candidate_version=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT
    fi
```
